### ISSUE TITLE
Incompatible with Tornado 6.0

### ISSUE THREAD

**Issue by jbms** [mrjoes/sockjs-tornado#117]
Tornado 6.0 removes tornado.web.asynchronous, which is used by sockjs-tornado.

As Tornado 6.0 is the current stable version for Python3, this means installing sockj-tornado on Python3 does not work by default.

**Comment by mrjoes** [comment]
I'll have to come up with a migration plan. Tornado 6.0 no longer supports Python 2.7 plus sockjs-tornado will have to be fixed up to use the new APIs.

This will definitely break the compatibility with the previous Tornado versions and Python 2.7 going forward.

**Comment by blokhin** [comment]
Dear Serge @mrjoes SockJS-Tornado is very nice and it's a great pity to refuse of it. If you ever get a chance to return to it, please, let us know.

**Comment by bronan99** [comment]
@mrjoes Any word on when/if Tornado 6 will be supported?

**Comment by davvid** [comment]
I can at least verify that @vane's solution in #118 works here with tornado 6.0.3.  Because tornado6 requires `async`, would you be more willing to take a similar change that instead uses `async` instead of the vendored `asynchronous` decorator?

In other words, because we know tornado6 is a breaking change that abandons python2, would you be happier with a solution that *doesn't* keep backwards-compatibility?

Perhaps a transition plan could be something simple like, "please test the tornado6 branch for now", and after some time support for python2 can be dropped when it goes to master?

**Comment by vane** [comment]
> I can at least verify that @vane's solution in #118 works here with tornado 6.0.3. Because tornado6 requires `async`, would you be more willing to take a similar change that instead uses `async` instead of the vendored `asynchronous` decorator?

Thanks @davvid ,
I will probably do the change to current code to support async instead of decorator and newest tornado but I don't have exact date when it will happen I barely started python 3 migration tasks.
