### ISSUE TITLE
Compatibility with Sock-js 1.0.0

### ISSUE THREAD

**Issue by jvetterick** [mrjoes/sockjs-tornado#81]
Is sockjs-tornado compatible with sock-js 1.0.0? Last sock-js version v1.0.0-beta.12 is from Feb 2015.

Especially the heartbeats since 0.4.0 are interesting: https://github.com/sockjs/sockjs-protocol/wiki/Heartbeats-and-SockJS

**Comment by arnuschky** [comment]
I tried sockjs 1.0.0 with tornado-sockjs and it seemed to work, mostly. All iframe-based transports failed, but this might also be due to a problem in the sockjs build

**Comment by FZambia** [comment]
SockJS 1.0 has no server protocol incompatible changes. To make iframe-based transport work provide URL to SockJS 1.0 javascript client [instead of 0.3.4](https://github.com/mrjoes/sockjs-tornado/blob/master/sockjs/tornado/router.py#L25) when initializing SockJSRouter. [Example](https://github.com/centrifugal/centrifuge/blob/master/centrifuge/node.py#L112) where `user_settings` is
```python
user_settings = {
    "sockjs_url": "https://cdn.jsdelivr.net/sockjs/1.0/sockjs.min.js"
}
```

**Comment by arnuschky** [comment]
Works fine, thanks a lot!

**Comment by jvetterick** [comment]
Seems to work for me, too
